#!/bin/bash
# Quick ACE Testing Commands
# Run these in the TUI to validate ACE integration

echo "=== ACE Testing Quick Reference ==="
echo ""
echo "📋 Step 1: Check Status"
echo "   cd /home/thetu/code/codex-rs"
echo "   code"
echo "   /speckit.ace-status"
echo ""
echo "📋 Step 2: Test Constitution"
echo "   /speckit.constitution"
echo "   /speckit.ace-status  # Verify bullets added"
echo ""
echo "📋 Step 3: Test Injection"
echo "   /speckit.plan SPEC-KIT-069"
echo "   # Look for: '⏳ Preparing prompt with ACE context...'"
echo ""
echo "📋 Step 4: Check Logs"
echo "   tail -50 ~/.code/logs/codex-tui.log | grep -i ace"
echo ""
echo "📋 Step 5: Monitor Growth"
echo "   sqlite3 ~/.code/ace/playbooks_normalized.sqlite3 \"SELECT scope, COUNT(*), AVG(score) FROM playbook_bullet GROUP BY scope;\""
echo ""
echo "=== Database Quick Queries ==="
echo ""
echo "# Current state:"
sqlite3 ~/.code/ace/playbooks_normalized.sqlite3 "SELECT scope, COUNT(*) as bullets, AVG(score) as avg_score FROM playbook_bullet GROUP BY scope;"
echo ""
echo "# Top bullets:"
sqlite3 ~/.code/ace/playbooks_normalized.sqlite3 "SELECT pb.scope, substr(b.text, 1, 60) as bullet, pb.score, pb.pinned FROM playbook_bullet pb JOIN bullet b ON pb.bullet_id = b.id ORDER BY pb.score DESC LIMIT 10;"
echo ""
echo "=== Logs to Watch ==="
echo ""
echo "# ACE initialization:"
echo "grep 'ACE MCP client initialized' ~/.code/logs/codex-tui.log | tail -5"
echo ""
echo "# Bullet injection:"
echo "grep 'Injected.*ACE bullets' ~/.code/logs/codex-tui.log | tail -5"
echo ""
echo "# Reflection/Curation:"
echo "grep -E '(Reflector|Curator)' ~/.code/logs/codex-tui.log | tail -10"
echo ""
echo "=== Success Criteria ==="
echo "✅ Status shows 8 bullets (global:6, tasks:1, test:1)"
echo "✅ Constitution extracts 7 bullets"
echo "✅ Injection shows 'Preparing with ACE context'"
echo "✅ Logs show bullet loading"
echo "✅ Playbook grows with use (8 → 15-25 bullets after 5-10 runs)"
echo ""
echo "See ACE_TEST_PLAN.md for detailed testing guide"
